# Generated by Django 2.1.4 on 2018-12-28 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=64, verbose_name='用户名')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.SmallIntegerField(choices=[(0, 'login'), (1, 'cmd'), (2, 'logout')], default=1, verbose_name='日志类型')),
                ('content', models.CharField(max_length=255, verbose_name='日志内容')),
                ('record_date', models.DateTimeField(auto_now_add=True, verbose_name='记录日期')),
                ('crazyeye_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='堡垒机账号')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('ip_addr', models.CharField(max_length=64, unique=True, verbose_name='ip地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口号')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='HostToRemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Host')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='IDC机房名')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('auth_type', models.SmallIntegerField(choices=[(0, 'ssh-password'), (1, 'ssh-key')], verbose_name='认证方式')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='remoteuser',
            unique_together={('username', 'password', 'auth_type')},
        ),
        migrations.AddField(
            model_name='hosttoremoteuser',
            name='remote_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.RemoteUser'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='host_to_remote_users',
            field=models.ManyToManyField(to='monitor.HostToRemoteUser'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.IDC'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='host_to_remote_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.HostToRemoteUser'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_group',
            field=models.ManyToManyField(to='monitor.HostGroup', verbose_name='主机组'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='host_to_remote_users',
            field=models.ManyToManyField(to='monitor.HostToRemoteUser', verbose_name='关联主机账户'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='hosttoremoteuser',
            unique_together={('host', 'remote_user')},
        ),
    ]
