# Generated by Django 2.1.4 on 2018-12-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='crazyeye_account',
            new_name='crazy_eye_account',
        ),
    ]
