# Generated by Django 2.1.4 on 2019-01-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20181231_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='用户名'),
        ),
    ]
