# Generated by Django 2.1.4 on 2019-01-06 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20190105_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cmd', '批量命令'), ('file_upload', '文件上传'), ('file_download', '文件下载')], default='cmd', max_length=16)),
                ('content', models.CharField(max_length=255, verbose_name='任务内容')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(verbose_name='任务执行结果')),
                ('status', models.SmallIntegerField(choices=[(0, 'initialized'), (1, 'sucess'), (2, 'failed'), (3, 'timeout')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('host_to_remote_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.HostToRemoteUser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Task')),
            ],
        ),
    ]
