# Generated by Django 2.1.4 on 2019-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_host_os_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('cmd', '批量命令'), ('file_upload', '传送本地文件到远程'), ('file_download', '从远程下载文件')], default='cmd', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近登录时间'),
        ),
    ]
